// Code generated by "stringer -type=FileStatus,AccessMode,FormMode,PositionMode,ActionMode,BlankMode,DelimMode,PadMode,DecimalMode,RoundMode,SignMode,AdvanceMode,CloseStatus,AsyncMode,EncodingMode,YesNoUnknown -linecomment -output stringers.go ."; DO NOT EDIT.

package fortio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUNKNOWN-0]
	_ = x[StatusOLD-1]
	_ = x[StatusNEW-2]
	_ = x[StatusREPLACE-3]
	_ = x[StatusSCRATCH-4]
}

const _FileStatus_name = "UNKNOWNOLDNEWREPLACESCRATCH"

var _FileStatus_index = [...]uint8{0, 7, 10, 13, 20, 27}

func (i FileStatus) String() string {
	if i >= FileStatus(len(_FileStatus_index)-1) {
		return "FileStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileStatus_name[_FileStatus_index[i]:_FileStatus_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessSEQUENTIAL-0]
	_ = x[AccessDIRECT-1]
	_ = x[AccessSTREAM-2]
}

const _AccessMode_name = "SEQUENTIALDIRECTSTREAM"

var _AccessMode_index = [...]uint8{0, 10, 16, 22}

func (i AccessMode) String() string {
	if i >= AccessMode(len(_AccessMode_index)-1) {
		return "AccessMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccessMode_name[_AccessMode_index[i]:_AccessMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormFORMATTED-0]
	_ = x[FormUNFORMATTED-1]
}

const _FormMode_name = "FORMATTEDUNFORMATTED"

var _FormMode_index = [...]uint8{0, 9, 20}

func (i FormMode) String() string {
	if i >= FormMode(len(_FormMode_index)-1) {
		return "FormMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FormMode_name[_FormMode_index[i]:_FormMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PositionASIS-0]
	_ = x[PositionREWIND-1]
	_ = x[PositionAPPEND-2]
}

const _PositionMode_name = "ASISREWINDAPPEND"

var _PositionMode_index = [...]uint8{0, 4, 10, 16}

func (i PositionMode) String() string {
	if i >= PositionMode(len(_PositionMode_index)-1) {
		return "PositionMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PositionMode_name[_PositionMode_index[i]:_PositionMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionREADWRITE-0]
	_ = x[ActionREAD-1]
	_ = x[ActionWRITE-2]
}

const _ActionMode_name = "READWRITEREADWRITE"

var _ActionMode_index = [...]uint8{0, 9, 13, 18}

func (i ActionMode) String() string {
	if i >= ActionMode(len(_ActionMode_index)-1) {
		return "ActionMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionMode_name[_ActionMode_index[i]:_ActionMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BlankNULL-0]
	_ = x[BlankZERO-1]
}

const _BlankMode_name = "NULLZERO"

var _BlankMode_index = [...]uint8{0, 4, 8}

func (i BlankMode) String() string {
	if i >= BlankMode(len(_BlankMode_index)-1) {
		return "BlankMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BlankMode_name[_BlankMode_index[i]:_BlankMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DelimNONE-0]
	_ = x[DelimAPOSTROPHE-1]
	_ = x[DelimQUOTE-2]
}

const _DelimMode_name = "NONEAPOSTROPHEQUOTE"

var _DelimMode_index = [...]uint8{0, 4, 14, 19}

func (i DelimMode) String() string {
	if i >= DelimMode(len(_DelimMode_index)-1) {
		return "DelimMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DelimMode_name[_DelimMode_index[i]:_DelimMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PadYES-0]
	_ = x[PadNO-1]
}

const _PadMode_name = "YESNO"

var _PadMode_index = [...]uint8{0, 3, 5}

func (i PadMode) String() string {
	if i >= PadMode(len(_PadMode_index)-1) {
		return "PadMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PadMode_name[_PadMode_index[i]:_PadMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DecimalPOINT-0]
	_ = x[DecimalCOMMA-1]
}

const _DecimalMode_name = "POINTCOMMA"

var _DecimalMode_index = [...]uint8{0, 5, 10}

func (i DecimalMode) String() string {
	if i >= DecimalMode(len(_DecimalMode_index)-1) {
		return "DecimalMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DecimalMode_name[_DecimalMode_index[i]:_DecimalMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoundPROCESSOR_DEFINED-0]
	_ = x[RoundNEAREST-1]
	_ = x[RoundUP-2]
	_ = x[RoundDOWN-3]
	_ = x[RoundZERO-4]
	_ = x[RoundCOMPATIBLE-5]
}

const _RoundMode_name = "PROCESSOR_DEFINEDNEARESTUPDOWNZEROCOMPATIBLE"

var _RoundMode_index = [...]uint8{0, 17, 24, 26, 30, 34, 44}

func (i RoundMode) String() string {
	if i >= RoundMode(len(_RoundMode_index)-1) {
		return "RoundMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RoundMode_name[_RoundMode_index[i]:_RoundMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SignPROCESSOR_DEFINED-0]
	_ = x[SignPLUS-1]
	_ = x[SignSUPPRESS-2]
}

const _SignMode_name = "PROCESSOR_DEFINEDPLUSSUPPRESS"

var _SignMode_index = [...]uint8{0, 17, 21, 29}

func (i SignMode) String() string {
	if i >= SignMode(len(_SignMode_index)-1) {
		return "SignMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SignMode_name[_SignMode_index[i]:_SignMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AdvanceYES-0]
	_ = x[AdvanceNO-1]
}

const _AdvanceMode_name = "YESNO"

var _AdvanceMode_index = [...]uint8{0, 3, 5}

func (i AdvanceMode) String() string {
	if i >= AdvanceMode(len(_AdvanceMode_index)-1) {
		return "AdvanceMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AdvanceMode_name[_AdvanceMode_index[i]:_AdvanceMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CloseKEEP-0]
	_ = x[CloseDELETE-1]
}

const _CloseStatus_name = "KEEPDELETE"

var _CloseStatus_index = [...]uint8{0, 4, 10}

func (i CloseStatus) String() string {
	if i >= CloseStatus(len(_CloseStatus_index)-1) {
		return "CloseStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CloseStatus_name[_CloseStatus_index[i]:_CloseStatus_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AsyncNO-0]
	_ = x[AsyncYES-1]
}

const _AsyncMode_name = "NOYES"

var _AsyncMode_index = [...]uint8{0, 2, 5}

func (i AsyncMode) String() string {
	if i >= AsyncMode(len(_AsyncMode_index)-1) {
		return "AsyncMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AsyncMode_name[_AsyncMode_index[i]:_AsyncMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EncodingDEFAULT-0]
	_ = x[EncodingUTF8-1]
}

const _EncodingMode_name = "DEFAULTUTF-8"

var _EncodingMode_index = [...]uint8{0, 7, 12}

func (i EncodingMode) String() string {
	if i >= EncodingMode(len(_EncodingMode_index)-1) {
		return "EncodingMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EncodingMode_name[_EncodingMode_index[i]:_EncodingMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InquiryUNKNOWN-0]
	_ = x[InquiryYES-1]
	_ = x[InquiryNO-2]
}

const _YesNoUnknown_name = "UNKNOWNYESNO"

var _YesNoUnknown_index = [...]uint8{0, 7, 10, 12}

func (i YesNoUnknown) String() string {
	if i >= YesNoUnknown(len(_YesNoUnknown_index)-1) {
		return "YesNoUnknown(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _YesNoUnknown_name[_YesNoUnknown_index[i]:_YesNoUnknown_index[i+1]]
}
